FSM:
  _:
    Passive: {id: 1}
    FixStand: {id: 2}
    Velocity_Up: {id: 4, type: RLBase}
    Velocity_Down: {id: 5, type: RLBase}
    Velocity_Left: {id: 6, type: RLBase}
    Velocity_Right: {id: 7, type: RLBase}
    Velocity_WalkTheseWay: {id: 8, type: RLBase}
  Passive:
    transitions: {FixStand: LT + A.on_pressed}
    mode: [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
    kd: [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]
  FixStand:
    transitions: {Passive: LT + B.on_pressed, Velocity_Up: start + up, Velocity_Down: start
        + down, Velocity_Left: start + left, Velocity_Right: start + right, Velocity_WalkTheseWay: start
        + r}
    kp: [60, 80, 80, 60, 80, 80, 60, 80, 80, 60, 80, 80]
    kd: [5, 4, 4, 5, 4, 4, 5, 4, 4, 5, 4, 4]
    ts: [0, 1, 2]
    qs:
    - []
    - [0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65, 0.0, 1.36, -2.65]
    - [0.0, 0.8, -1.5, 0.0, 0.8, -1.5, 0.0, 1.0, -1.5, 0.0, 1.0, -1.5]
  Velocity_Up:
    transitions: {Pas